language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t k4wesome/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true k4wesome/docker-react npm run test -- --coverage
